os: linux
language: python
dist: bionic
git:
  depth: false


jobs:
  include:
    - env:
        - CHANNEL="defaults"
        - PYDIST="ANACONDA"
      python: "3.6"
    - env:
        - CHANNEL="conda-forge"
        - PYDIST="ANACONDA"
      python: "3.8"
    - name: "3.7 with bionic"
      python: "3.7"

install:
  # Setup anaconda following http://conda.pydata.org/docs/travis.html
  - if [[ "$PYDIST" == "ANACONDA" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda info -a;
      conda create -q -n test-environment -c $CHANNEL python=$TRAVIS_PYTHON_VERSION scipy matplotlib;
      source activate test-environment;
    fi
  - python --version
  - pip install .
  - pip install PyYAML
  - pip install coveralls

script:
  - make test_with_coverage

after_success:
  - coveralls
